### ISSUE TITLE
Language translation added

### ISSUE THREAD

**Issue by GodSayFK** [DavyVerbogt/Colt-s-Cosmetic-Armor-Mod#2]
I am sorry.
I do not know how to use "Pull request".
I translated it into traditional Chinese.
You can put it in the module.
Your mod is really cool.

===============I am the divider line===================

{
    "itemGroup.ccamTab": "Colt's Cosmetic Armour Mod",
    "itemGroup.ccamTabCurio": "Colt's Cosmetic Armour Mod Curio",
    "item.ccam.witch_hat": "女巫帽",
    "item.ccam.colt_helmet": "蒸汽龐克護目鏡",
    "item.ccam.colt_chestplate": "蒸汽龐克外套",
    "item.ccam.colt_leggings": "蒸汽龐克外套下擺",
    "item.ccam.tulip_hat": "鬱金香",
    "item.ccam.flower_crown": "花冠",
    "item.ccam.top_hat": "禮帽",
    "item.ccam.cowboy_hat": "牛仔帽",
    "item.ccam.traffic_cone": "交通錐",
    "item.ccam.monocle": "單片眼鏡",
    "item.ccam.small_top_hat": "小禮帽",
    "item.ccam.basic_helmet": "§b基本頭盔",
    "item.ccam.basic_chestplate": "§b基本胸甲",
    "item.ccam.basic_leggings": "§b基本護腿",
    "item.ccam.basic_boots": "§b基本靴子",
    "block.ccam.sewing_station": "縫紉機",
    "item.ccam.construction_helmet": "§6安全帽",
    "item.ccam.gladiator_helmet": "百夫長頭盔",
    "item.ccam.gladiator_chestplate": "百夫長胸甲",
    "item.ccam.gladiator_leggings": "百夫長護腿",
    "item.ccam.gladiator_boots": "百夫長靴",
    "item.ccam.japaneseconstruction_helmet": "§6安全帽",
    "item.ccam.nacho_sombrero": "Nacho墨西哥帽",
    "item.ccam.sombrero": "墨西哥帽",
    "item.ccam.wolf_helmet": "狼皮帽",
    "item.ccam.wolf_chestplate": "狼皮大衣",
    "item.ccam.wolf_leggings": "狼皮褲",
    "item.ccam.wolf_boots": "狼皮靴",
    "item.ccam.arrow_through_head": "箭頭穿過你的頭",
    "item.ccam.long_small_top_hat": "長款小禮帽",
    "item.ccam.long_top_hat": "長禮帽",
    "item.ccam.top_top_top_hat": "疊高高禮帽",
    "item.ccam.curio_top_hat": "禮帽",
    "item.ccam.cat_ears": "貓耳朵",
    "item.ccam.dog_ears": "狗耳朵",
    "item.ccam.rabbit_ears": "兔耳朵",
    "item.ccam.cat_tail": "貓尾巴",
    "item.ccam.dog_tail": "狗尾巴",
    "item.ccam.rabbit_tail": "兔尾",
    "item.ccam.basic_curio": "§b基本腰帶",
    "item.ccam.samurai_helmet": "武士頭盔",
    "item.ccam.samurai_chestplate": "武士胸甲",
    "item.ccam.samurai_leggings": "武士護腿",
    "item.ccam.samurai_boots": "武士靴",
    "item.ccam.cow_helmet": "牛頭套",
    "item.ccam.cow_chestplate": "牛胸甲",
    "item.ccam.cow_leggings": "牛綁腿",
    "item.ccam.cow_boots": "牛靴",
    "item.ccam.shot_cowboy_hat": "彈痕牛仔帽",
    "item.ccam.fur_coat": "皮毛大衣",
    "item.ccam.straw_hat": "草帽",
    "item.ccam.halo": "光環",
    "item.ccam.poncho": "斗篷",
    "item.ccam.poncho_side": "披風側身",
    "item.ccam.spur": "馬刺",
    "item.ccam.sunglasses": "太陽鏡",
    "item.ccam.milestone_glasses": "感謝10000下載-眼鏡",
    "item.ccam.milestone_shirt": "感謝10000下載-下載襯衫",
    "item.ccam.milestone_chain": "感謝10000下載-下載項鍊",

    "curios.identifier.feet": "Feet",
    "curios.identifier.tail": "Tail"
}

**Comment by GiraffeSummer** [comment]
Woah, that's sick, We'll try to add it asap!

Thank you so much!

**Comment by GiraffeSummer** [comment]
We've added it into the 1.18 version, hopefully it works.
thanks so much for translating it for us, we'll put you in the credit's if you'll like (let us know if you have a specific name or something in mind)
